name: check biome
on:
  push:
  # 手動実行設定
  workflow_dispatch:

jobs:
  build-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # jobの連続実行を防ぐ
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run biome check
        run: npm run check
